use mongodb::bson::oid::ObjectId;
use rocket::{fs::TempFile, http::ContentType};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]

pub struct User {
    pub _id: Option<ObjectId>,
    pub name: Option<String>,
    pub password: String,
    pub email: String,
    pub role: Option<i32>, // 0 | 1: Admin | User
    pub auth_token: Option<String>, //generated by backend
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct File {
    pub _id: Option<ObjectId>,
    pub owned_by: Option<String>,
    pub name: Option<String>,
    pub path: Option<String>,
    pub size: Option<u64>,
}

#[derive(FromForm, Debug)]
pub struct Upload<'r>{
    pub file:TempFile<'r>    
}