use mongodb::bson::oid::ObjectId;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]

pub struct User {
    pub _id: Option<ObjectId>,
    pub name: Option<String>,
    pub password: String,
    pub email: String,
    pub role: Option<i32>, // 0 | 1: Admin | User
    pub auth_token: Option<String>, //generated by backend
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct File {
    pub _id: Option<ObjectId>,
    pub owned_by: ObjectId,
    pub name: String,
    pub size: i64,
    file: Vec<u8>
}